---
- name: download .deb file
  get_url:
    dest=/tmp/logstash_1.4.0-1-c82dc09_all.deb
    url=https://download.elasticsearch.org/logstash/logstash/packages/debian/logstash_1.4.0-1-c82dc09_all.deb
    mode=0644
  tags:
    - logstash
    - install
    - packages

- name: install from .deb package
  command: dpkg --skip-same-version --force-depends --install {{ temp_dir }}/logstash_1.4.0-1-c82dc09_all.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  notify:
    - restart logstash
    - restart logstash web
  tags:
    - logstash
    - install
    - packages
