---
- name: Logstash | Check to see if download exists
  stat:
    path: "{{ logstash_download_path }}/logstash_1.5.0-1_all.deb"
  register: logstash_download_check
  tags:
    - logstash
    - install
    - packages

- name: Logstash | download .deb file
  get_url:
    dest: "{{ logstash_download_path }}/logstash_1.5.0-1_all.deb"
    url: "http://download.elastic.co/logstash/logstash/packages/debian/logstash_1.5.0-1_all.deb"
    mode: 0644
  register: logstash_downloaded
  when: logstash_download_check is defined and logstash_download_check.stat.exists == false
  tags:
    - logstash
    - install
    - packages

- name: Logstash | install from .deb package
  command: "dpkg --skip-same-version -i {{ logstash_download_path }}/logstash_1.5.0-1_all.deb"
  when: (logstash_download_check is defined and logstash_download_check.stat.exists == true) or logstash_downloaded|changed
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  register: dpkg_result
  sudo: yes
  notify:
    - restart logstash
  tags:
    - logstash
    - install
    - packages