---
- name: Add Elasticsearch apt key.
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present
  when: logstash_version | version_compare('1.4', operator='eq', strict=True)

- name: Add Logstash repository.
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/logstash/1.4/debian stable main'
    state: present
  when: logstash_version | version_compare('1.4', operator='eq', strict=True)

- name: Check if Logstash is already installed.
  stat: path=/etc/init.d/logstash
  register: logstash_installed

- name: Update apt cache if repository just added.
  apt: update_cache=yes
  when: logstash_installed.stat.exists == false

- name: Install Logstash.
  apt: pkg=logstash state=present

- name: Add Logstash user to adm group (Debian).
  user:
    name: logstash
    group: logstash
    groups: adm
  when: ansible_os_family == "Debian"
  notify: restart logstash

- name: Stop Logstash Web
  service:
    name: logstash-web
    state: stopped
    enabled: no

- name: Disable Logstash Web
  copy:
    dest: /etc/init/logstash-web.override
    content: "manual\n"
    owner: root
    group: root
    mode: 644
